"""
Django settings for fstr_project project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os  
from decouple import config  

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  

SECRET_KEY = config('SECRET_KEY', default='your_secret_key_here')  

DEBUG = config('DEBUG', default=False, cast=bool)  

ALLOWED_HOSTS = ['*']   

INSTALLED_APPS = [  
    'django.contrib.admin',  
    'django.contrib.auth',  
    'django.contrib.contenttypes',  
    'django.contrib.sessions',  
    'django.contrib.messages',  
    'django.contrib.staticfiles',  
    'corsheaders',  
    'rest_framework',  
    'pereval',  
]  

MIDDLEWARE = [  
    'corsheaders.middleware.CorsMiddleware',  
    'django.middleware.security.SecurityMiddleware',  
    'django.contrib.sessions.middleware.SessionMiddleware',  
    'django.middleware.common.CommonMiddleware',  
    'django.middleware.csrf.CsrfViewMiddleware',  
    'django.contrib.auth.middleware.AuthenticationMiddleware',  
    'django.contrib.messages.middleware.MessageMiddleware',  
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  
]  

ROOT_URLCONF = 'fstr_project.urls'  

TEMPLATES = [  
    {  
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  
        'DIRS': [],  
        'APP_DIRS': True,  
        'OPTIONS': {  
            'context_processors': [  
                'django.template.context_processors.debug',  
                'django.template.context_processors.request',  
                'django.contrib.auth.context_processors.auth',  
                'django.contrib.messages.context_processors.messages',  
            ],  
        },  
    },  
]  

WSGI_APPLICATION = 'fstr_project.wsgi.application'  

DATABASES = {  
    'default': {  
        'ENGINE': 'django.db.backends.postgresql',  
        'NAME': config('FSTR_DB_NAME'),  
        'USER': config('FSTR_DB_LOGIN'),  
        'PASSWORD': config('FSTR_DB_PASS'),  
        'HOST': config('FSTR_DB_HOST'),  
        'PORT': config('FSTR_DB_PORT'),  
    }  
}  

AUTH_PASSWORD_VALIDATORS = [  
    {  
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',  
    },  
    {  
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',  
    },  
    {  
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',  
    },  
    {  
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',  
    },  
]  

LANGUAGE_CODE = 'en-us'  

TIME_ZONE = 'UTC'  

USE_I18N = True  

USE_L10N = True  

USE_TZ = True  

STATIC_URL = '/static/'  

CORS_ALLOWED_ORIGINS = [  
    'http://localhost:3000',  
    'http://localhost',
    'http://127.0.0.1',
]  

# Security settings  
SECURE_BROWSER_XSS_FILTER = True  
SECURE_CONTENT_TYPE_NOSNIFF = True