# Generated by Django 5.1.4 on 2024-12-04 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pereval',
            name='add_time',
        ),
        migrations.AlterField(
            model_name='pereval',
            name='connect',
            field=models.TextField(default='Дорога ведет через горы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pereval',
            name='coord',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pereval.coords'),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='other_titles',
            field=models.CharField(blank=True, default='Нет других названий', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pereval',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('new', 'New'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=50),
        ),
    ]
